#!/bin/bash

# this is a awfully done script to render my paper using a single
# command. As you can see, my bash scripting powers are somewhat
# limited.


rm GPU_Raytracer.aux
rm GPU_Raytracer.bbl
rm GPU_Raytracer.blg
rm GPU_Raytracer.dvi
rm GPU_Raytracer.log
rm GPU_Raytracer.pdf

pdflatex GPU_Raytracer &&
bibtex GPU_Raytracer &&
pdflatex GPU_Raytracer &&
pdflatex GPU_Raytracer
